### ISSUE TITLE
Switch from opusscript to a faster alternative

### ISSUE THREAD

**Issue by ohlookitsderpy** [MoeRadio/Moe#1]
**Is your feature request related to a problem? Please describe.**
no it isn't

**Describe the solution you'd like**
opusscript has been mentioned in the discord.js github (see [here](https://github.com/discordjs/discord.js#audio-engines)) as not suitable for production. Lavalink, as an example, is a lot faster with better audio quality. It also supports having servers in multiple regions, so you can get better audio signal and quality wherever you are.

**Describe alternatives you've considered**
node-opus is also an ok option (saying that because it is *slightly* better) if you cant't/don't want to setup Lavalink "nodes". (you can just run one on the main vps if needed, as a note).

**Additional context**
[Lavalink Github](https://github.com/Frederikam/Lavalink)
[Lavalink discord.js lib link](https://github.com/MrJacz/discord.js-lavalink)
[node-opus npm](https://npmjs.com/package/node-opus)

**Comment by etcroot** [comment]
Will consider changing it to lavalink, contacted you on discord.
